const environment = process.env.ENVIRONMENT === 'production' ? 'prod' : 'staging'

const AGGREGATES_UPDATE_TODAY_REGULAR_CRON = environment === 'prod' ? '4,19,34,49 * * * *' : '6 * * * *'
const SEDO_AGGREGATES_UPDATE_YESTERDAY_AFTER_MIDNIGHT_AND_NOON = '20 2,6,8,12 * * *'
const CROSSROADS_AGGREGATES_UPDATE_YESTERDAY_AFTER_MIDNIGHT_AND_NOON = '20 11,17 * * *'

module.exports = {
  AGGREGATES_UPDATE_TODAY_REGULAR_CRON,
  SEDO_AGGREGATES_UPDATE_YESTERDAY_AFTER_MIDNIGHT_AND_NOON,
  CROSSROADS_AGGREGATES_UPDATE_YESTERDAY_AFTER_MIDNIGHT_AND_NOON
}
