const EnvironmentVariablesManager = require('../../../../shared/services/EnvironmentVariablesManager');
const environment = EnvironmentVariablesManager.getEnvVariable('CRON_ENVIRONMENT') === 'production' ? 'prod' : 'staging'

const AGGREGATES_UPDATE_TODAY_REGULAR_CRON = environment === 'prod' ? '4,19,34,49 * * * *' : '6 * * * *'
const SEDO_AGGREGATES_UPDATE_YESTERDAY_AFTER_MIDNIGHT_AND_NOON = '30 0,7,9,11 * * *'
const CROSSROADS_AGGREGATES_UPDATE_YESTERDAY_AFTER_MIDNIGHT_AND_NOON = '20 11,17 * * *'
const TONIC_AGGREGATES_UPDATE_YESTERDAY_AFTER_MIDNIGHT_AND_NOON = '20 11,17 * * *'

module.exports = {
  AGGREGATES_UPDATE_TODAY_REGULAR_CRON,
  SEDO_AGGREGATES_UPDATE_YESTERDAY_AFTER_MIDNIGHT_AND_NOON,
  CROSSROADS_AGGREGATES_UPDATE_YESTERDAY_AFTER_MIDNIGHT_AND_NOON,
  TONIC_AGGREGATES_UPDATE_YESTERDAY_AFTER_MIDNIGHT_AND_NOON
}
