version: '3'

services:
  postgres:
    image: postgres:12
    container_name: 'digittopia_postgres'
    env_file: '.env'
    ports:
      - '5433:5432'

  memcached:
    image: memcached:1.5
    container_name: 'efflux_memcached'
    command: memcached -m 64
    env_file: '.env'
    ports:
      - '11211:11211'

  express_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'digittopia_express'
    ports:
      - '5000:5000'
    environment:
      - REDIS_HOST=redis
      - DATABASE_HOST=postgres
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
    volumes:
      - ./logs:/logs
    depends_on:
      - redis
      - postgres
