version: "3"

services:
  postgres:
    image: postgres:12
    container_name: "digittopia_postgres"
    env_file: ".env"
    ports:
      - "5432:5432"
  redis:
    image: redis
    container_name: "digittopia_redis"
    command: redis-server
    env_file: ".env"
    ports:
      - "6379:6379"
