version: "3"

services:
  postgres:
    image: postgres:12
    container_name: "digittopia_postgres"
    env_file: ".env"
    ports:
      - "5433:5432"

  redis:
    image: redis
    container_name: "digittopia_redis"
    command: redis-server
    env_file: ".env"
    ports:
      - "6379:6379"

  express_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "digittopia_express"
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
      - DATABASE_HOST=postgres
    depends_on:
      - redis
      - postgres
