AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Campaign Launch Trigger

Globals:
  Function:
    Timeout: 5
    Architectures:
      - arm64
    MemorySize: 128
    Runtime: nodejs20.x
    AutoPublishAlias: live
    DeploymentPreference:
      Enabled: true
      Type: AllAtOnce
    Tags:
      project: efflux

Resources:
  # Add a dynamodb table with key "internal_campaign_id" and sort field "status"
  # Enable dynamodb streams
  InternalCampaignsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: in-progress-campaigns
      AttributeDefinitions:
        - AttributeName: internal_campaign_id
          AttributeType: S
        - AttributeName: status
          AttributeType: S
      KeySchema:
        - AttributeName: internal_campaign_id
          KeyType: HASH
        - AttributeName: status
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      Tags:
        - Key: project
          Value: efflux
        - Key: operation
          Value: analytics

  CampaignLaunchDynamoTriggerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./handlers
      Handler: dynamo.handler
      FunctionName: campaign-launch-trigger-dynamo
      Description: A Lambda function to trigger the launch of campaigns -
        transition them from draft to published
      Role: !GetAtt LambdaFunctionRole.Arn
      Policies:
        - DynamoDBStreamReadPolicy:
            TableName: !Ref InternalCampaignsTable
            StreamName: !GetAtt InternalCampaignsTable.StreamArn
        - DynamoDBCrudPolicy:
            TableName: !Ref InternalCampaignsTable
        - SQSSendMessagePolicy:
            QueueName: !Ref ReadyToLaunchCampaignsQueue
        - SQSPollerPolicy:
            QueueName: !Ref ReadyToLaunchCampaignsDLQ
      Environment:
        Variables:
          SQS_QUEUE_URL: !Ref ReadyToLaunchCampaignsQueue
          DYNAMODB_TABLE_NAME: !Ref InternalCampaignsTable
      Events:
        DynamoDBStream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt InternalCampaignsTable.StreamArn
            BatchSize: 1
            StartingPosition: LATEST

  CampaignLaunchSNSTriggerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./handlers
      Handler: sns.handler
      FunctionName: campaign-launch-trigger-sns
      Description: A Lambda function to trigger the launch of campaigns -
        transition them from draft to published
      Role: !GetAtt LambdaFunctionRole.Arn
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !Ref ReadyToLaunchCampaignsQueue
        - DynamoDBCrudPolicy:
            TableName: !Ref InternalCampaignsTable
        - SNSCrudPolicy:
            TopicName: !ImportValue MediaMaster-SNSTopicArn
      Environment:
        Variables:
          SQS_QUEUE_URL: !Ref ReadyToLaunchCampaignsQueue
          SNS_TOPIC_ARN: !ImportValue MediaMaster-SNSTopicArn
          DYNAMODB_TABLE_NAME: !Ref InternalCampaignsTable
      Events:
        SNS:
          Type: SNS
          Properties:
            Topic: !ImportValue MediaMaster-SNSTopicArn

  WriteToDynamoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./handlers
      Handler: dynamo-writer.handler
      FunctionName: writer-of-dynamo-inprogress-campaigns
      Description: A Lambda function to write to dynamo db an in-progress campaign
      Role: !GetAtt LambdaFunctionRole.Arn
      Policies:
        - DynamoDBStreamReadPolicy:
            TableName: !Ref InternalCampaignsTable
            StreamName: !GetAtt InternalCampaignsTable.StreamArn
        - DynamoDBCrudPolicy:
            TableName: !Ref InternalCampaignsTable
        - SQSSendMessagePolicy:
            QueueName: !Ref WriteToDynamoQueue
        - SQSPollerPolicy:
            QueueName: !Ref WriteToDynamoDLQ
      Environment:
        Variables:
          SQS_QUEUE_URL: !Ref WriteToDynamoQueue
          DYNAMODB_TABLE_NAME: !Ref InternalCampaignsTable
      Events:
        SqsEvent:
          Type: SQS
          Properties:
            Enabled: true
            Queue: !GetAtt WriteToDynamoQueue.Arn
            BatchSize: 10

  WriteToDynamoQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: write-inprogress-campaigns
      DelaySeconds: 420  # Delay delivery of messages by 7 minutes
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt WriteToDynamoDLQ.Arn
        maxReceiveCount: 3
      Tags:
        - Key: project
          Value: efflux
        - Key: operation
          Value: launcher

  WriteToDynamoDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: write-inprogress-campaigns-dlq
      Tags:
        - Key: project
          Value: efflux
        - Key: operation
          Value: launcher

  ReadyToLaunchCampaignsQueue:
    Type: AWS::SQS::Queue
    UpdateReplacePolicy: Retain
    DeletionPolicy: Delete
    Properties:
      QueueName: campaigns-ready-to-launch
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt ReadyToLaunchCampaignsDLQ.Arn
        maxReceiveCount: 3
      Tags:
        - Key: Name
          Value: campaigns-ready-to-launch
        - Key: project
          Value: efflux
  
  ReadyToLaunchCampaignsDLQ:
    Type: AWS::SQS::Queue
    UpdateReplacePolicy: Retain
    DeletionPolicy: Delete
    Properties:
      QueueName: campaigns-ready-to-launch-dlq
      Tags:
        - Key: Name
          Value: campaigns-ready-to-launch-dlq
        - Key: project
          Value: efflux

  LambdaFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
        - arn:aws:iam::aws:policy/AmazonSQSFullAccess
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowLambdaServiceToAssumeRole
            Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - lambda.amazonaws.com
      Tags:
        - Key: project
          Value: efflux
