CREATE TABLE crossroads_events (
  click_timestamp Datetime,
  network_campaign_id String,
  network_campaign_name String,
  network_campaign_type String,
  network_campaign_number String,
  category String,
  pixel_id String,
  src_campaign_id String,
  src_campaign_name String,
  adset_name String,
  adset_id String,
  ad_id String,
  traffic_source String,
  session_id String,
  clientIp String,
  country String,
  region String,
  city String,
  external String,
  timestamp String,
  user_agent String,
  conversions String,
  revenue Float32,
  keyword_clicked String,
  account String,
  lander_searches Int32,
  lander_visitors Int32,
  tracked_visitors Int32,
  total_visitors Int32,
  unique_identifier String
)
    engine = MergeTree
    PRIMARY KEY (click_timestamp, src_campaign_id)
