CREATE TABLE insights (
    org_id Int32,
    date String,
    hour smallint,
    campaign_id String,
    campaign_name String,
    adset_id String,
    adset_name String,
    user_id Int32,
    ad_account_id Int32,
    revenue Float32,
    spend Float32,
    spend_plus_fee Float32,
    link_clicks Int32,
    ts_conversions Nullable(Int32),
    nw_conversions Nullable(Int32),
    nw_uniq_conversions Nullable(Int32),
    pb_conversions Int32,
    searches Int32,
    lander_visits Int32,
    visitors Int32,
    tracked_visitors Int32,
    impressions Int32,
    traffic_source String,
    unique_identifier String,
    unallocated_revenue Float32,
    unallocated_spend Float32,
    unallocated_spend_plus_fee Float32,
    ts_clicks Int32,
    ts_updated_at timestamp,
    pb_lander_conversions Int32,
    pb_serp_conversions Int32,
    network_updated_at timestamp,
    network String
)
    engine = MergeTree
    PRIMARY KEY (org_id, campaign_id)
