CREATE TABLE new_insights (
    org_id Int32,
    visit_id String, -- calculate elapsed time between visit_id and event_time
    campaign_id String,
    campaign_name String,
    network_campaign_id String,
    network_campaign_name String,
    adset_id String,
    adset_name String,
    user_id Int32,
    ad_account_id Int32,
    revenue Float32,
    spend Float32,
    spend_plus_fee Float32,
    link_clicks Int32,
    nbr_of_searches Int32,
    nbr_of_visitors Int32,
    nbr_of_tracked_visitors Int32,
    nbr_of_impressions Int32,
    nbr_of_lander_visits Int32,
    unique_identifier String,
    unallocated_revenue Float32,
    unallocated_spend Float32,
    unallocated_spend_plus_fee Float32,
    traffic_source_conversions Nullable(Int32),
    traffic_source String,
    traffic_source_clicks Int32,
    traffic_source_updated_at DateTime,
    postback_conversions Int32,
    postback_lander_conversions Int32,
    postback_serp_conversions Int32,
    network_conversions Nullable(Int32),
    network_uniq_conversions Nullable(Int32),
    network_updated_at DateTime,
    network String
)
    engine = MergeTree
    PRIMARY KEY (org_id, visit_id)
