CREATE TABLE postbacks (
  event_id String,
  event_timestamp String,
  received_at Nullable(String),
  event_type Nullable(String),
  event_network Nullable(String),
  network_campaign_id String,
  network_campaign_name Nullable(String),
  network_campaign_number Nullable(String),
  ad_id Nullable(String),
  ad_name Nullable(String),
  adset_id Nullable(String),
  adset_name Nullable(String),
  ad_account_id Nullable(String),
  ad_account_name Nullable(String),
  keyword_clicked Nullable(String),
  requested_with Nullable(String),
  origin Nullable(String),
  host Nullable(String),
  browser Nullable(String),
  device Nullable(String),
  os Nullable(String),
  referer Nullable(String),
  traffic_source Nullable(String),
  session_id Nullable(String),
  client_ip Nullable(String),
  country Nullable(String),
  region Nullable(String),
  city Nullable(String),
  is_direct Nullable(Int8),
  is_conversion Nullable(Int8),
  preestimated_revenue Nullable(Float32),
  estimated_revenue Nullable(Float32),
  estimated_revenue_5h Nullable(Float32),
  revenue Nullable(Float32)
  domain Nullable(String),
  pixel_id Nullable(String),
  external Nullable(String),
  fb_click_id Nullable(String),
  transaction_id Nullable(String),
  conversions Nullable(Int32),
  posted_to_fb Nullable(Int8),
  is_fb_crawler Nullable(Int8),
)
engine = MergeTree
PRIMARY KEY (event_timestamp, network_campaign_id)
