CREATE TABLE postbacks_2 (
  event_id String,
  visit_id Nullable(String),
  event_time DateTime,
  received_at Nullable(DateTime),
  event_type Nullable(String),
  event_network Nullable(String),
  network_campaign_id String,
  network_campaign_name Nullable(String),
  network_campaign_number Nullable(String),
  ad_id Nullable(String),
  ad_name Nullable(String),
  adset_id Nullable(String),
  adset_name Nullable(String),
  ad_account_id Nullable(String),
  ad_account_name Nullable(String),
  keyword_clicked Nullable(String),
  step Nullable(Int32),
  network_revenue Nullable(Float32),
  network_revenue_type Nullable(Int32), -- type 0 = final; type 1 = estimation_1, type 2 = estimation_2
  efflux_revenue Nullable(Float32),
  requested_with Nullable(String),
  origin Nullable(String),
  host Nullable(String),
  browser Nullable(String),
  device Nullable(String),
  os Nullable(String),
  referer Nullable(String),
  traffic_source Nullable(String),
  client_ip Nullable(String),
  country Nullable(String),
  region Nullable(String),
  city Nullable(String),
  domain Nullable(String),
  pixel_id Nullable(String),
  external Nullable(String),
  fb_click_id Nullable(String),
  posted_to_fb Nullable(Int32),
  is_direct Nullable(Int32),
  is_conversion Nullable(Int32), -- a visit can have multiple conversions
  is_fb_crawler Nullable(Int32),
  is_google_crawler Nullable(Int32),
)
engine = MergeTree
PRIMARY KEY (event_timestamp, network_campaign_id)
