CREATE TABLE sedo_events (
  event_id String,
  received_timestamp String,
  event_timestamp String,
  event_type String,
  network_campaign_id String,
  network_campaign_name String,
  domain String,
  ad_id String,
  ad_name String,
  pixel_id String,
  adset_id String,
  traffic_source String,
  transaction_id String,
  session_id String,
  client_ip String,
  country String,
  region String,
  city String,
  device String,
  os String,
  browser String,
  external String,
  conversions Int8,
  revenue Float32,
  keyword_clicked String,
)
engine = MergeTree
PRIMARY KEY (event_timestamp, network_campaign_id, session_id)
