CREATE TABLE tonic_events (
  event_id String,
  received_timestamp String,
  event_timestamp String,
  event_type String,
  network_campaign_id String,
  network_campaign_name String,
  pixel_id String,
  adset_id String,
  adset_name String,
  ad_id String,
  traffic_source String,
  session_id String,
  client_ip String,
  country String,
  region String,
  city String,
  external String,
  conversions Int32,
  revenue Float32,
  keyword_clicked String,  
  is_fb_crawler Int8,
)
engine = MergeTree
PRIMARY KEY (event_timestamp, network_campaign_id, session_id)
