class AdMetadata {
    constructor(
        id, // assuming it's auto-incremented by the database
        name,
        status,
        creative_name,
        page_id,
        asset_feed_spec, // JSON object
        ad_id,
        created_at, // auto-generated by knex
        updated_at  // auto-generated by knex
    ) {
        this.id = id;
        this.name = name || ''; // default to empty string if not provided
        this.status = status || 'PAUSED'; // default to 'PAUSED' if not provided
        this.creative_name = creative_name || '';
        this.page_id = page_id || '';
        this.asset_feed_spec = asset_feed_spec || '{}'; // default to empty JSON object if not provided
        this.ad_id = ad_id || '';
        this.created_at = created_at;
        this.updated_at = updated_at;
    }
}

module.exports = AdMetadata;
