class AdsetMetadata {
    constructor(
        id, // assuming it's auto-incremented by the database
        name,
        status,
        daily_budget,
        special_ad_category,
        special_ad_category_country,
        dsa_beneficiary,
        dsa_payor,
        optimization_goal,
        billing_event,
        is_dynamic_creative,
        age_min,
        age_max,
        countries,
        user_os,
        gender,
        click_through,
        view_through,
        pixel_id,
        adset_id, // foreign key reference to another table (table name and column name should be specified)
        created_at, // auto-generated by knex
        updated_at  // auto-generated by knex
    ) {
        this.id = id;
        this.name = name;
        this.status = status;
        this.daily_budget = daily_budget;
        this.special_ad_category = special_ad_category;
        this.special_ad_category_country = special_ad_category_country;
        this.dsa_beneficiary = dsa_beneficiary;
        this.dsa_payor = dsa_payor;
        this.optimization_goal = optimization_goal;
        this.billing_event = billing_event;
        this.is_dynamic_creative = is_dynamic_creative;
        this.age_min = age_min;
        this.age_max = age_max;
        this.countries = countries;
        this.user_os = user_os;
        this.gender = gender;
        this.click_through = click_through;
        this.view_through = view_through;
        this.pixel_id = pixel_id;
        this.adset_id = adset_id;
        this.created_at = created_at;
        this.updated_at = updated_at;
    }
}

module.exports = AdsetMetadata;
