FACEBOOK_REVEALBOT_SHEET_REGULAR_CRON = '14-59/15 * * * *';
TIKTOK_REVEALBOT_SHEET_REGULAR_CRON = '58 * * * *';

module.exports = {
  FACEBOOK_REVEALBOT_SHEET_REGULAR_CRON,
  TIKTOK_REVEALBOT_SHEET_REGULAR_CRON
};
