name: Staging Build and Deploy

on:
  push:
    branches:
      - staging

jobs:
  build-and-deploy:
    name: 'Build and deploy to staging'
    runs-on: self-hosted

    if: contains('refs/heads/staging', github.ref)
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build and Deploy using Docker Compose
        run: |
          cd /home/ubuntu/goerge-efflux-platform
          git checkout ${GITHUB_REF#refs/heads/}
          git pull origin ${GITHUB_REF#refs/heads/}
          
          # Stopping and removing all containers
          docker-compose down

          # Building and starting services in detached mode
          docker-compose up --build -d 

          # Cleaning up unused resources
          docker system prune -f --volumes
