name: Staging Build and Deploy

on:
  push:
    branches:
      - staging

jobs:
  build-and-deploy:
    name: 'Build and deploy to staging'
    runs-on: self-hosted

    if: contains('refs/heads/staging', github.ref)
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build and Deploy using Docker Compose
        run: |
          cd /home/ubuntu/goerge-efflux-platform
          git checkout ${GITHUB_REF#refs/heads/}
          git pull origin ${GITHUB_REF#refs/heads/}
          docker-compose down # Stop and remove all containers defined in docker-compose.yml
          docker-compose build # Build services defined in docker-compose.yml
          docker-compose up -d # Start services in detached mode
          docker system prune -f --volumes
