name: Staging Build and Deploy

on:
  push:
    branches:
      - staging

jobs:
  build-and-deploy:
    name: 'Build and deploy to staging'
    runs-on: ubuntu-latest

    if: contains('refs/heads/staging', github.ref)
    steps:
      - name: remote commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STAGING_SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.STAGING_SSH_PRIVATE_KEY }}
          port: ${{ secrets.STAGING_SSH_PORT }}
          script: |
            cd goerge-efflux-platform
            git checkout ${GITHUB_REF#refs/heads/}
            git pull origin ${GITHUB_REF#refs/heads/}
            docker-compose down # Stop and remove all containers defined in docker-compose.yml
            docker-compose build # Build services defined in docker-compose.yml
            docker-compose up -d # Start services in detached mode
            docker system prune -f --volumes
