name: Master Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: 'Build and deploy to Master'
    runs-on: [self-hosted, master-runner]  # This specifies that the workflow should use the self-hosted runner with the "master-runner" label.

    if: contains('refs/heads/master', github.ref)
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build and Deploy using Docker Compose
        run: |
          cd ~/goerge-efflux-platform
          git checkout ${GITHUB_REF#refs/heads/}
          git pull origin ${GITHUB_REF#refs/heads/}
          
          # Exporting AWS credentials to be used by Docker
          echo "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" > .env.aws
          echo "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" >> .env.aws
          echo "AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}" >> .env.aws

          # Stopping and removing all containers
          docker-compose down

          # Building and starting services in detached mode
          docker-compose up --build -d 

          # Cleaning up unused resources
          docker system prune -f --volumes
